name: nexplay
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  animated_read_more_text: ^0.0.6
  google_fonts: ^6.2.1
  change_app_package_name: ^1.3.0
  firebase_core: ^3.4.0
  cloud_firestore: ^5.4.0
  firebase_auth: ^5.2.0
  firebase_storage: ^12.2.0
  fluttertoast: ^8.2.8
  flutter_native_splash: ^2.4.1
  google_nav_bar: ^5.0.6
  get: ^4.6.6
  flutter_svg: ^2.0.10+1
  skeletonizer: ^1.4.2
  custom_rating_bar: ^3.0.0
  searchfield: ^1.1.0
  pinch_zoom: ^2.0.0
  lottie: ^3.1.2
  auto_size_text: ^3.0.0
  json_theme_plus: ^6.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/theme.json


flutter_native_splash:
  android: true
  ios: true
  web: false

  color: '#050505'
  image: "assets/splash_screen/2.png"

  android_12:
    color: '#050505'
    image: "assets/splash_screen/2.png"
  