name: nexplay
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  animated_read_more_text: ^0.0.6
  auto_size_text: ^3.0.0
  change_app_package_name: ^1.3.0
  cloud_firestore: ^5.4.0
  cupertino_icons: ^1.0.6
  custom_rating_bar: ^3.0.0
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  firebase_storage: ^12.2.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.8
  font_awesome_flutter: ^10.7.0
  get: ^4.6.6
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.6
  http: ^1.2.2
  image_picker: ^1.1.2
  language_picker: ^0.4.5
  lottie: ^3.1.2
  pinch_zoom: ^2.0.0
  searchfield: ^1.1.0
  shared_preferences: ^2.3.2
  skeletonizer: ^1.4.2
  smooth_page_indicator: ^1.2.0+3
  youtube_player_flutter: ^9.1.0
  device_preview: ^1.2.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/animations/

  fonts:
    - family: ProzaLibre
      fonts:
        - asset: assets/fonts/ProzaLibre-Regular.ttf
        - asset: assets/fonts/ProzaLibre-Bold.ttf
          weight: 700
        - asset: assets/fonts/ProzaLibre-Italic.ttf
          style: italic
        - asset: assets/fonts/ProzaLibre-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/ProzaLibre-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/ProzaLibre-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/ProzaLibre-Medium.ttf
          weight: 500
        - asset: assets/fonts/ProzaLibre-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/ProzaLibre-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ProzaLibre-SemiBoldItalic.ttf
          weight: 600
          style: italic

flutter_native_splash:
  android: true
  ios: true
  web: false

  color: '#050505'
  image: "assets/splash_screen/2.png"

  android_12:
    color: '#050505'
    image: "assets/splash_screen/2.png"
